<div style="text-align:left;font-size:2em"><span style="font-weight:bolder;font-size:1.25em">SP2273 | Learning Portfolio</span><br><br><span style="font-weight:bold;color:darkred">Storing Data (Good) Exercises</span></div>

## Exercise 1

| Term | Brief Description |
| :-- | :--: |
| Subsetting | Selecting data often with a condition |
| Indexing | Accessing _one_ element based on its position with the first element being 0 indexed |
| Slicing | Accessing elemets with a range from start to stop (exclusive) and steps |
| Masking | Masking applies a condition to an array or list to produce True/False values (Boolean mask). You can then use this mask to filter elements that satisfy the condition. |

## Exercise 2

In [ ]:
import numpy as np
np_array_2d = np.array([[1, "A"], [3, "C"], [2, "B"], [4, "D"],
                        [5, "E"], [7, "G"], [6, "F"], [8, "H"],
                        [10, "J"], [9, "I"]])

first_elements = np_array_2d[:,0] # access all rows, first column only
int_first_elements = first_elements.astype(int) # convert to integers
odd_numbers = int_first_elements % 2 # Even number = 0, odd number = 1
odd_numbers_check = odd_numbers == 1

letters = (np_array_2d[:, 1])
odd_letters = letters[odd_numbers_check] # NumPy looks at letters array and check where odd_numbers_check is true
print(odd_letters)


['A' 'C' 'E' 'G' 'I']


## Exercise 3

In [22]:
data = [[66, 50, 57, -1, -1],
 [92, -1, 88, -1, -1],
 [75, -1, -1, 76, -1],
 [-1, 51, 87, -1, -1],
 [71, -1, 67, -1, 69]]

import numpy as np
np_data = np.array(data)

# replacing values below 50 to -1
mask_1 = np_data < 50
np_data[mask_1] = -1

# replacing values above 50 to +1
mask_2 = np_data > 50
np_data[mask_2] = +1

# replacing values equal to 50 to 0
mask_3 = np_data == 50
np_data[mask_3] = 0

print(np_data)


[[ 1  0  1 -1 -1]
 [ 1 -1  1 -1 -1]
 [ 1 -1 -1  1 -1]
 [-1  1  1 -1 -1]
 [ 1 -1  1 -1  1]]
